services:

  # СЕРВИС 1: База данных для Inventory Service
  inventory-db:
    # Используем официальный образ PostgreSQL 15 (alpine - маленький)
    image: postgres:15-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # Проброс портов: внешний:внутренний
    ports:
      - "5435:5432"
    volumes:
      - inventory-data:/var/lib/postgresql/data
    # Healthcheck - проверка, что сервис здоров
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-service:
    build: ./inventory-service
    container_name: inventory-microservice
    ports:
      - "8081:8080"
    depends_on:
      inventory-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db

  # СЕРВИС 2: База для Order Service
  order-db:
    image: postgres:15-alpine
    container_name: order-postgres
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

  # СЕРВИС 3: Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  # порт для подключения
      ZOOKEEPER_TICK_TIME: 2000    # настройки таймаута
    ports:
      - "2181:2181"  # открываем порт

  # СЕРВИС 4: Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    # Зависимости: Kafka не запустится без Zookeeper
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # подключение к Zookeeper
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # автоматически создавать топики
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 3

  # СЕРВИС 5: Kafka UI
#  #TODO: не работает
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    depends_on:
#      kafka:
#        condition: service_healthy
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#    ports:
#      - "8080:8080"  # веб-интерфейс будет на http://localhost:8080

  # СЕРВИС 6: База для Notification Service
  notification-db:
    image: postgres:15-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - notification-data:/var/lib/postgresql/data

# Тома (volumes) - постоянное хранилище данных
volumes:
  inventory-data:
  order-data:
  notification-data:
